### ISSUE TITLE
这个长期维护么

### ISSUE THREAD

**Issue by iszmxw** [aoxiang594/laravel-province-city-area#4]
先关注

**Comment by iszmxw** [comment]
不能获取所有城市列表，所有区域列表，只能获取所有省份列表，希望能优化一下，方便更多的人

**Comment by 9yearfish** [comment]
## 长期维护呀

另外你那边是怎么用的，我这边没发现你说的问题啊。
我们已经在线上项目正常使用啦。
![image](https://user-images.githubusercontent.com/11186536/59900741-af79a400-942b-11e9-8a8c-e5dbac58c5ae.png)

**Comment by iszmxw** [comment]
我说的是“所有”，不是某个省份下的城市

**Comment by iszmxw** [comment]
把三百多个城市列出来，以及上千个区域列出来，而不是通过省份去匹配市，然后再去匹配区域

**Comment by 9yearfish** [comment]
ProvinceCityArea::getAllProvince();
ProvinceCityArea::getAllCity()
ProvinceCityArea::getAllStreet()

建议不要这样用，获取所有街道的时候，一下子要取出四万条数据了

**Comment by iszmxw** [comment]
主要是想获取所有市，街道其实没有那个需求
