### ISSUE TITLE
强制从京东获取 失败

### ISSUE THREAD

**Issue by gyp719** [aoxiang594/laravel-province-city-area#6]
开发环境 ：homestead ，laravel 5.8

强制从京东获取，请执行php artisan pca:refreshData -d jd

![image](https://user-images.githubusercontent.com/30563368/82397760-b5389900-9a83-11ea-87fa-3ad2cd17a4b4.png)

php artisan pca:refreshData 获取的数据不完整

**Comment by 9yearfish** [comment]
1、要么选择用本地数据，包里面有提供
2、要么重试一下，有可能网络问题。
3、要么composer update，刚从社区过来的，看到你回复了。
